/*
 * The MIT License
 *
 * Copyright 2014 mkdr <makedir@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package gui;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 *
 * @author mkdr <makedir@gmail.com>
 */
public class OverlayGui extends javax.swing.JFrame {

    HashMap activeBEvents;
    HashMap activePreEvents;
    
    /**
     * Creates new form OverlayGui
     */
    public OverlayGui() {
        
        this.activeBEvents = new HashMap();
        this.activePreEvents = new HashMap();
        
        initComponents();
    }

    public void setTranslations(String activeBEventsLabel, String activePreEventsLabel) {
        
        this.jLabel1.setText(activeBEventsLabel);
        this.jLabel2.setText(activePreEventsLabel);
    }
    
    public void clearActive() {
        
        this.activeBEvents.clear();
        this.activePreEvents.clear();
    }
    
    public void addActiveB(String name, String color) {
        
        this.activeBEvents.put(name, color);
    }
    
    public void addActivePreEvent(String name, String color) {
        
        this.activePreEvents.put(name, color);
    }
    
    public void renderActive() {
        
        String outBsTmp = "";
        String outPresTmp = "";
        
        Iterator it = this.activeBEvents.entrySet().iterator();
                    
        while (it.hasNext()) {

            Map.Entry pairs = (Map.Entry) it.next();

            String name = (String) pairs.getKey();
            String color = (String) pairs.getValue();
            
            if (color.equals("yellow")) {
                outBsTmp = outBsTmp + "<b><font color=yellow>" + name + "</font></b><br>";
            } else {
                outBsTmp = outBsTmp + "<b>" + name + "</b><br>";
            }
            
            it.remove();
        }
        
        it = this.activePreEvents.entrySet().iterator();
                    
        while (it.hasNext()) {

            Map.Entry pairs = (Map.Entry) it.next();

            String name = (String) pairs.getKey();
            String color = (String) pairs.getValue();
            
            if (color.equals("yellow")) {
                outPresTmp = outPresTmp + "<b><font color=yellow>" + name + "</font></b><br>";
            } else {
                outPresTmp = outPresTmp + "<b>" + name + "</b><br>";
            }
            
            it.remove();
        }
        
        if (outBsTmp.equals("")) {
            outBsTmp = "-";
        } else {
            outBsTmp = "<html>" + outBsTmp + "</html>";
        }
        
        if (outPresTmp.equals("")) {
            outPresTmp = "-";
        } else {
            outPresTmp = "<html>" + outPresTmp + "</html>";
        }
        
        this.jLabelActiveBs.setText(outBsTmp);
        this.jLabelActivePres.setText(outPresTmp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelActiveBs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelActivePres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GW2 Eventer overlay");
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("active B events:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1);

        jLabelActiveBs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelActiveBs.setForeground(new java.awt.Color(102, 255, 0));
        jLabelActiveBs.setText("-");
        jLabelActiveBs.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelActiveBs);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("active pre Events:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2);

        jLabelActivePres.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelActivePres.setForeground(new java.awt.Color(102, 255, 0));
        jLabelActivePres.setText("-");
        jLabelActivePres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelActivePres);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelActiveBs;
    private javax.swing.JLabel jLabelActivePres;
    // End of variables declaration//GEN-END:variables
}
